version: '3.8'

services:
  web:
    tty: true
    init: true
    working_dir: /web
    ports: [80:80]
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      - ./web:/web:cached
      - ./web/node_modules:/web/node_modules:delegated
    build:
      context: ./web
      target: dev-stage
  #   depends_on:
  #     - graph

  # graph:
  #   ports: [4000:4000]
  #   volumes:
  #     - './graphql:/app'
  #     - ./graphql/node_modules:/app/node_modules:delegated
  #   working_dir: '/app'
  #   build:
  #     context: ./graphql
  #     target: dev-stage
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #       max_attempts: 3
