version: '3.8'

services:
  web:
    tty: true
    init: true
    working_dir: /web
    ports: [80:80]
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    volumes:
      - ./web:/web:cached
      - ./web/node_modules:/web/node_modules:delegated
    build:
      context: ./web
      target: dev-stage
